2023.07.18 checkpoint: Just squarewave-ish. Decent

diff --git a/patch-airsense b/patch-airsense
--- a/patch-airsense
+++ b/patch-airsense
@@ -87,28 +87,32 @@ patch_code_ventilator() {
 
 
 patch_code_graph() {
-	patch_pointer patches/graph.bin 0xfd000 0xf9c88 '\x01\xd0\x0f\x08'
+	patch_pointer patches/graph.bin 0xfcd40 0xf9c88 '\x41\xcd\x0f\x08'
+	# patch_pointer patches/graph.bin 0xfd000 0xf9c88 '\x01\xd0\x0f\x08'
 }
 
 # Replaces not_called_during_loop
 patch_code_squarewave() {
-	patch_pointer patches/squarewave.bin 0xfd300 0xf9778 '\x01\xd3\x0f\x08'
+	patch_pointer patches/squarewave.bin 0xfd000 0xf9778 '\x01\xd0\x0f\x08'
 }
 
 patch_code_squarewave_asv() {
-	patch_pointer patches/squarewave_asv.bin 0xfd300 0xf9778 '\x01\xd3\x0f\x08'
+	patch_pointer patches/squarewave_asv.bin 0xfd000 0xf9778 '\x01\xd0\x0f\x08'
 }
 
 patch_code_squarewave_pav() {
-	patch_pointer patches/squarewave_pav.bin 0xfd300 0xf9778 '\x01\xd3\x0f\x08'
+	patch_pointer patches/squarewave_pav.bin 0xfd000 0xf9778 '\x01\xd0\x0f\x08'
 }
 
 
 patch_code_easybreathe() {
 	die "Patching this function not allowed, shit goes haywire, not sure why"
-	patch_pointer patches/easybreathe.bin 0xfe368 0xf886c '\x69\xe3\x0f\x08'
+	patch_pointer patches/easybreathe.bin 0xfdf00 0xf886c '\x01\xdf\x0f\x08' # Replaces `pressure_work`
+	# patch_pointer patches/easybreathe.bin 0xfdf00 0xf96e8 '\x01\xdf\x0f\x08' # Replaces `compute_pressure_stuff_replaced_with_breath`
+	# This replaces an instruction that jumps to `pressure_timed_ramp` with a jump to `0xfdf00`
+	# To change, use Ghidra to patch the instruction and copy the modified bytes to the printf 
+	# printf '\x42\xf0\xe6\xf8' | patch 0xbbd30 || die " patching failed"
 }
-
 
 patch_code() {
 	if [[ $PATCH_CODE == 1 ]] ; then
