2023.09.23 checkpoint: Added the ASV backup rate disable patch, sorted some stuff

diff --git a/patch-airsense b/patch-airsense
--- a/patch-airsense
+++ b/patch-airsense
@@ -87,31 +87,39 @@ patch_code_ventilator() {
 
 
 patch_code_graph() {
+	echo "Patching graphing code"
 	patch_pointer patches/graph.bin 0xfcd40 0xf9c88 '\x41\xcd\x0f\x08'
 	# patch_pointer patches/graph.bin 0xfd000 0xf9c88 '\x01\xd0\x0f\x08'
 }
 
 # Replaces not_called_during_loop
 patch_code_squarewave() {
+	echo "Patching Squarewave"
 	patch_pointer patches/squarewave.bin 0xfd000 0xf9778 '\x01\xd0\x0f\x08'
 }
 
 patch_code_squarewave_asv() {
+	echo "Patching Squarewave ASV"
 	patch_pointer patches/squarewave_asv.bin 0xfd000 0xf9778 '\x01\xd0\x0f\x08'
 }
 
-patch_code_squarewave_pav() {
-	patch_pointer patches/squarewave_pav.bin 0xfd000 0xf9778 '\x01\xd0\x0f\x08'
-}
+# patch_code_squarewave_pav() {
+# 	patch_pointer patches/squarewave_pav.bin 0xfd000 0xf9778 '\x01\xd0\x0f\x08'
+# }
 
 
-patch_code_easybreathe() {
-	die "Patching this function not allowed, shit goes haywire, not sure why"
-	patch_pointer patches/easybreathe.bin 0xfdf00 0xf886c '\x01\xdf\x0f\x08' # Replaces `pressure_work`
-	# patch_pointer patches/easybreathe.bin 0xfdf00 0xf96e8 '\x01\xdf\x0f\x08' # Replaces `compute_pressure_stuff_replaced_with_breath`
-	# This replaces an instruction that jumps to `pressure_timed_ramp` with a jump to `0xfdf00`
-	# To change, use Ghidra to patch the instruction and copy the modified bytes to the printf 
-	# printf '\x42\xf0\xe6\xf8' | patch 0xbbd30 || die " patching failed"
+# patch_code_easybreathe() {
+# 	die "Patching this function not allowed, shit goes haywire, not sure why"
+# 	patch_pointer patches/easybreathe.bin 0xfdf00 0xf886c '\x01\xdf\x0f\x08' # Replaces `pressure_work`
+# 	# patch_pointer patches/easybreathe.bin 0xfdf00 0xf96e8 '\x01\xdf\x0f\x08' # Replaces `compute_pressure_stuff_replaced_with_breath`
+# 	# This replaces an instruction that jumps to `pressure_timed_ramp` with a jump to `0xfdf00`
+# 	# To change, use Ghidra to patch the instruction and copy the modified bytes to the printf 
+# 	# printf '\x42\xf0\xe6\xf8' | patch 0xbbd30 || die " patching failed"
+# }
+
+patch_code_asv_task_wraper() {
+	echo "Patching ASV task wrapper"
+	patch_pointer patches/asv_task_wrapper.bin 0xfdf00 0xf44e0 '\x01\xdf\x0f\x08'
 }
 
 patch_code() {
@@ -119,12 +127,14 @@ patch_code() {
 		BUILD_FLAGS=$(( BUILD_FLAGS | (1 << 0) ))
 		echo "Patching code"
 		patch_code_graph
-		if [[ $PATCH_ASV == 1 ]] ; then
+		if [[ $PATCH_S_ASV == 1 ]] ; then
 			patch_code_squarewave_asv
-		elif [[ $PATCH_PAV == 1 ]] ; then 
-			patch_code_squarewave_pav
-		else
+		elif [[ $PATCH_S == 1 ]] ; then
 			patch_code_squarewave
+		fi
+
+		if [[ $PATCH_ASV_TASK_WRAPPER == 1 ]] ; then
+			patch_code_asv_task_wraper
 		fi
 		# patch_code_easybreathe
 	fi
@@ -140,6 +150,20 @@ unlock_ui_limits() {
 	printf '\xdc\x05\x00\x00\x32\x00' | patch 0x7ecc || die failed
 }
 
+asv_unlock_ps_range () {
+    BUILD_FLAGS=$(( BUILD_FLAGS | (1 << 7) ))
+
+    # Disable the ASV and ASVAuto PS range check to allow Max PS < (Min PS + 5)
+    #
+    # Update PS validation logic without disabling other checks.
+    printf '\x00' | patch 0x76c08
+    printf '\x00' | patch 0x76c34
+    printf '\x00' | patch 0x76cca
+
+    # Update variable config to allow Max PS to be set below 5
+    printf '\x00' | patch 0x8074
+    printf '\x00' | patch 0x8100
+}
 
 extra_debug() {
 	BUILD_FLAGS=$(( BUILD_FLAGS | (1 << 2) ))
@@ -207,6 +231,19 @@ gui_config () {
 	done
 }
 
+gui_config_all () {
+    BUILD_FLAGS=$(( BUILD_FLAGS | (1 << 7) ))
+    # Enable more settings and reported values by enabling bit 1 for all config variables
+    printf "patching 00004ef4 -> 0000833c (bit 0 for all 479 config variables)..."
+    for var in {0..478}
+    do
+        perl -p -0777 -i -e "substr(\$_, 0x4ef4 + ($var * 0x1c), 1) |= chr(1)" "$OUT"
+    done
+    printf " done.\n"
+}
+
+
+
 custom_palette() {
 	BUILD_FLAGS=$(( BUILD_FLAGS | (1 << 7) ))
 
@@ -241,19 +278,41 @@ custom_palette() {
 	done
 }
 
+asv_disable_backup_rate () {
+		echo "Patching ASV backup rate"
+    BUILD_FLAGS=$(( BUILD_FLAGS | (1 << 7) ))
+
+    # Add ASV task wrapper function to empty high flash space.
+    # This function suppresses the backup rate by overriding the breath percentage as needed, and then calls the normal ASV task.
+    # cat backupRate.bin | patch 0xff000 || die "backupRate patch failed"
+    #
+    # Expanded binary patch inline so it doesn't need to be compiled.
+    printf '\x09\x4b\xd3\xf8\x08\x38\x01\x2b\x0b\xd1\x08\x4b\xdf\xed\x08\x7a\x93\xed\x27\x7a\xb4\xee\xe7\x7a\xf1\xee\x10\xfa\xc8\xbf\xc3\xed\x27\x7a\x04\x4b\x18\x47\x00\xbf\x00\xe0\x00\x20\x00\xea\x00\x20\x48\xe1\x7a\x3f\x65\x34\x0e\x08' | patch 0xff000
+
+    # Patch ASV task to point to the wrapper function.
+    printf '\x01\xf0\x0f\x08' | patch 0xf44e0
+}
+
 check_hash
 
 patch_tamper
 patch_strings
 
+if [[ $PATCH_BACKUP_RATE == 1 ]] ; then
+	asv_disable_backup_rate
+fi
 patch_code # Handled based on environmental variables, no need to comment out
 
+# gui_config_all
 unlock_ui_limits # 2
 extra_debug # 4
 extra_modes # 8
 extra_menu # 16
 # all_menu # 32
 gui_config # 64
+
+asv_unlock_ps_range
+
 custom_palette #128
 
 # echo "Built with FLAGS=$BUILD_FLAGS"
